import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "@/components/Buttons/Providers";
import QueryProvider from "../queryProvider";
import AllMessages from "@/components/Chat/AllMessages";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
return (
 <html lang="en">
   <body
     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
   >
     <QueryProvider>
       <Providers>
         <div className="flex h-[calc(100vh-5rem)]">
           <div className="w-64 bg-gray-100 border-r">
             <AllMessages />
           </div>
           <div className="flex-1">
             {children}
           </div>
         </div>
       </Providers>
     </QueryProvider>
   </body>
 </html>
);
}
